### PR TITLE
Task/add bittrex

### PR DESCRIPTION
**Pull request by einsteinx2**
Added bittrex support including tests
Updated tests targets for Swift 4 (less boilerplate)

### CODE REVIEW

**Comment by jiashuw** [comment]
@einsteinx2 @wolffan hey guys, we need to merge this one otherwise some are too many issues w/ the current bittrex integration for mac client.

example:
- missing `ubq` rate.
- `bcc`(`bcash` symbol on bittrex) rate is wrong.

**Comment by einsteinx2** [comment]
This is actually live. I've fixed the client side now, and will add the BCC to BCH fix here and merge and push.

**Comment by einsteinx2** [comment]
I'll double check why we're not getting a rate for UBQ though.

**Comment by einsteinx2** [comment]
Actually I misspoke, I thought I pushed this live but I didn't, which would explain the missing UBQ rate. Getting this sorted now.

**Pull request merged**
